# Generated by Django 4.0.1 on 2024-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentsystemmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('erd', models.TextField(default=None, help_text='Drag and drop of a YML file is possible.', verbose_name='Competition Run Document (ERD without agents)')),
                ('is_public', models.BooleanField(default=False)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='created', max_length=20)),
                ('aborted_by_user', models.BooleanField(default=False)),
                ('attacker', models.ManyToManyField(related_name='attackers_competition', to='agentsystemmanagement.Agent')),
                ('defender', models.ManyToManyField(related_name='defender_competition', to='agentsystemmanagement.Agent')),
            ],
        ),
    ]
