{
 "title": "custom_newReward",
 "tags": [ "" ],
 "time": { "from": "2016-12-31T23:00:00.000Z", "to": "2017-01-01T22:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "experiment_id", "query": 41 },
   { "name": "start_date", "query": "2017-01-01 00:00:00+01:00" },
   { "name": "end_date", "query": "2017-01-02 00:00:00+01:00" },
   {
    "name": "agent_id",
    "query": "SELECT agents.id FROM agents\nLEFT JOIN experiment_run_phases ON agents.experiment_run_phase_id = experiment_run_phases.id\nLEFT JOIN experiment_run_instances ON experiment_run_phases.experiment_run_instance_id = experiment_run_instances.id\nLEFT JOIN experiment_runs ON experiment_run_instances.experiment_run_id = experiment_runs.id\nLEFT JOIN experiments ON experiment_runs.experiment_id = experiments.id\nWHERE CAST(experiment_runs.uid AS INTEGER) = $experiment_id"
   },
   {
    "name": "episode",
    "label": "Episode",
    "query": "SELECT DISTINCT episode FROM episodes WHERE episodes.muscle_action_id IN (SELECT id FROM muscle_actions WHERE muscle_actions.agent_id IN (SELECT agents.id FROM agents\nLEFT JOIN experiment_run_phases ON agents.experiment_run_phase_id = experiment_run_phases.id\nLEFT JOIN experiment_run_instances ON experiment_run_phases.experiment_run_instance_id = experiment_run_instances.id\nLEFT JOIN experiment_runs ON experiment_run_instances.experiment_run_id = experiment_runs.id\nLEFT JOIN experiments ON experiment_runs.experiment_id = experiments.id\nWHERE CAST(experiment_runs.uid AS INTEGER) = $experiment_id))"
   },
   {
    "name": "agent_1",
    "query": "SELECT agents.id FROM agents\nLEFT JOIN experiment_run_phases ON agents.experiment_run_phase_id = experiment_run_phases.id\nLEFT JOIN experiment_run_instances ON experiment_run_phases.experiment_run_instance_id = experiment_run_instances.id\nLEFT JOIN experiment_runs ON experiment_run_instances.experiment_run_id = experiment_runs.id\nLEFT JOIN experiments ON experiment_runs.experiment_id = experiments.id\nWHERE CAST(experiment_runs.uid AS INTEGER) = $experiment_id\nLIMIT 1 OFFSET 0"
   },
   {
    "name": "agent_2",
    "query": "SELECT agents.id FROM agents\nLEFT JOIN experiment_run_phases ON agents.experiment_run_phase_id = experiment_run_phases.id\nLEFT JOIN experiment_run_instances ON experiment_run_phases.experiment_run_instance_id = experiment_run_instances.id\nLEFT JOIN experiment_runs ON experiment_run_instances.experiment_run_id = experiment_runs.id\nLEFT JOIN experiments ON experiment_runs.experiment_id = experiments.id\nWHERE CAST(experiment_runs.uid AS INTEGER) = $experiment_id\nLIMIT 1 OFFSET 1\n"
   },
   {
    "name": "agent_1_name",
    "query": "SELECT name FROM agents\nWHERE id = $agent_1"
   },
   {
    "name": "agent_2_name",
    "query": "SELECT name FROM agents\nWHERE id = $agent_2"
   },
   { "name": "midas_startdate", "query": "2017-01-01 00:00:00" }
  ]
 },
 "panels": [
  { "title": "Analysis (simtime)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Busse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  time - '$midas_startdate'::TIMESTAMP + '$start_date'::TIMESTAMP+ '0 second'::interval AS \"time\",\n  pp_meta.name AS metric,\n  vm_pu\nFROM pp_bus, pp_bus_meta as pp_meta\nWHERE pp_meta.pp_index = pp_bus.pp_index and $__timeFilter(\"time\") and pp_meta.experiment_id = $experiment_id and pp_bus.experiment_id = $experiment_id ORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Environment Reward for selected Episode",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\", \nCASE WHEN (CAST(((rewards::json)::json-> 'grid_health_reward' ->> 'value') AS float)) IS NOT NULL \nTHEN CAST(((rewards::json)::json-> 'grid_health_reward' ->> 'value') AS float) \nELSE CAST(((rewards::json)::json->> 'grid_health_reward') AS float)  END as \"reward\"\nFROM muscle_actions \nLEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id\nWHERE episodes.episode = $episode\nAND muscle_actions.agent_id = $agent_id\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Line - loading percentage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT   time - '$midas_startdate'::TIMESTAMP + '$start_date'::TIMESTAMP+ '0 second'::interval AS \"time\",   CAST(pp_meta.pp_index AS VARCHAR) AS metric,   loading_percent \nFROM pp_line, pp_line_meta as pp_meta \nWHERE pp_meta.pp_index = pp_line.pp_index and $__timeFilter(\"time\") \nand pp_meta.experiment_id = $experiment_id and pp_line.experiment_id = $experiment_id \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Reward - MovingAverage 100",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT id - (SELECT min(id) FROM muscle_actions WHERE muscle_actions.agent_id = $agent_id) as \"actions\", AVG(CASE WHEN (CAST(((rewards::json)::json-> 'grid_health_reward' ->> 'value') AS float)) IS NOT NULL \nTHEN CAST(((rewards::json)::json-> 'grid_health_reward' ->> 'value') AS float) \nELSE CAST(((rewards::json)::json->> 'grid_health_reward') AS float)  END) OVER(ORDER BY id ROWS BETWEEN 100 PRECEDING AND CURRENT ROW) as \"moving average reward\"\nFROM muscle_actions\nWHERE muscle_actions.agent_id = $agent_id"
    }
   ]
  },
  {
   "title": "Trafo - Loading Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT   time - '$midas_startdate'::TIMESTAMP + '$start_date'::TIMESTAMP+ '0 second'::interval AS \"time\",   CAST(pp_meta.pp_index AS VARCHAR) AS metric,   loading_percent \nFROM pp_trafo, pp_trafo_meta as pp_meta \nWHERE pp_meta.pp_index = pp_trafo.pp_index and $__timeFilter(\"time\") \nand pp_meta.experiment_id = $experiment_id and pp_trafo.experiment_id = $experiment_id \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Average Episode Reward",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT episode, AVG(CASE WHEN (CAST(((rewards::json)::json-> 'grid_health_reward' ->> 'value') AS float)) IS NOT NULL \nTHEN CAST(((rewards::json)::json-> 'grid_health_reward' ->> 'value') AS float) \nELSE CAST(((rewards::json)::json->> 'grid_health_reward') AS float)  END) as \"average reward\"\nFROM muscle_actions, episodes\nWHERE muscle_actions.agent_id = $agent_id\nAND episodes.muscle_action_id = muscle_actions.id\nGROUP BY episode\nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Loads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time - '$midas_startdate'::TIMESTAMP + '$start_date'::TIMESTAMP+ '0 second'::interval AS \"time\",\n  pp_meta.name AS metric,\n  p_mw\nFROM pp_load, pp_load_meta as pp_meta\nWHERE pp_meta.pp_index = pp_load.pp_index and pp_meta.experiment_id = $experiment_id and pp_load.experiment_id = $experiment_id ORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Ext Grid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\n  time - '$midas_startdate'::TIMESTAMP + '$start_date'::TIMESTAMP+ '0 second'::interval AS \"time\",\n  pp_meta.name AS metric,\n  p_mw\nFROM pp_ext_grid, pp_ext_grid_meta as pp_meta\nWHERE pp_meta.pp_index = pp_ext_grid.pp_index and pp_meta.experiment_id = $experiment_id and pp_ext_grid.experiment_id = $experiment_id ORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Generators",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time - '$midas_startdate'::TIMESTAMP + '$start_date'::TIMESTAMP+ '0 second'::interval AS \"time\",\n  pp_meta.name AS metric,\n  p_mw\nFROM pp_static_generator as pp_sgen, pp_static_generator_meta as pp_meta\nWHERE pp_meta.pp_index = pp_sgen.pp_index and pp_meta.experiment_id = $experiment_id and pp_sgen.experiment_id = $experiment_id ORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Constraints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Constraint",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "rawSql": "SELECT\n  \"time\" AS \"Zeitstempel\",\n  (case \n  when \"type\" = 'trafo' \n    then \n      (SELECT name FROM pp_trafo_meta pp_meta \n      WHERE pp_meta.experiment_id=con.experiment_id \n      and pp_meta.pp_index=con.pp_index)\n  when \"type\" = 'line' \n    then \n      (SELECT name FROM pp_line_meta pp_meta \n      WHERE pp_meta.experiment_id=con.experiment_id \n      and pp_meta.pp_index=con.pp_index) \n  when \"type\" = 'load' \n    then \n      (SELECT name FROM pp_load_meta pp_meta \n      WHERE pp_meta.experiment_id=con.experiment_id \n      and pp_meta.pp_index=con.pp_index)\n  when \"type\" = 'sgen' \n    then \n      (SELECT name FROM pp_static_generator_meta pp_meta \n      WHERE pp_meta.experiment_id=con.experiment_id \n      and pp_meta.pp_index=con.pp_index) \n  else '0' \n  end) as \"Netzelement\",\n  key as \"Constraint\"\nFROM \"constraint\" as con\nWHERE\n  $__timeFilter(\"time\") and con.experiment_id = $experiment_id\nORDER BY 1"
      }
     ]
    }
   ]
  },
  { "title": "Actuator-Setpoints (simtime)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "$agent_1_name: load-actuator-setpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' AND agent_id = $agent_1 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "$agent_2_name: load-actuator-setpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' AND agent_id = $agent_2 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "$agent_1_name: sgen-actuator-setpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' AND agent_id = $agent_1 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "$agent_2_name: sgen-actuator-setpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' AND agent_id = $agent_2 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "$agent_1_name: switch-actuator-setpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%switch%' AND agent_id = $agent_1 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "$agent_2_name: switch-actuator-setpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%switch%' AND agent_id = $agent_2 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "$agent_1_name: trafo-actuator-setpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%trafo%' AND agent_id = $agent_1 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "$agent_2_name: trafo-actuator-setpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%trafo%' AND agent_id = $agent_2 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Actuator-Setpoints + Reward (walltime)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reward - walltime - MovingAvrage 96",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\n  walltime as \"time\",\n  AVG(CAST((rewards::json->'grid_health_reward' ->> 'value') AS float)) \n  OVER(ORDER BY walltime ROWS BETWEEN 96 PRECEDING AND CURRENT ROW) as \"reward\"\nFROM muscle_actions\nWHERE agent_id = $agent_id\norder by time asc "
      }
     ]
    },
    {
     "title": "Reward - walltime - MovingAvrage 96",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\n  walltime as \"time\",\n  CAST((rewards::json->'grid_health_reward' ->> 'value') AS float) \"reward\"\nFROM muscle_actions\nWHERE agent_id = $agent_id\norder by time asc "
      }
     ]
    },
    {
     "title": "$agent_1_name: actuator setpoints",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\nwalltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE metric LIKE '%load%' and agent_id = $agent_1 \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$agent_2_name: load-actuator setpoints (wt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\nwalltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE metric LIKE '%load%' and agent_id = $agent_2 \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$agent_1_name: sgen-actuator setpoints (wt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\nwalltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE metric LIKE '%sgen%' and agent_id = $agent_1 \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$agent_2_name: sgen-actuator setpoints (wt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT\nwalltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE metric LIKE '%sgen%' and agent_id = $agent_2 \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$agent_1_name: switch-actuator setpoints (wt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\nwalltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE metric LIKE '%switch%' and agent_id = $agent_1 \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$agent_2_name: switch-actuator setpoints (wt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "rawSql": "SELECT\nwalltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE metric LIKE '%switch%' and agent_id = $agent_2 \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$agent_1_name: trafo-actuator setpoints (wt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT\nwalltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE metric LIKE '%trafo%' and agent_id = $agent_1 \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "$agent_2_name: trafo-actuator setpoints (wt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "rawSql": "SELECT\nwalltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions,\njson_each(muscle_actions.actuator_setpoints::json) as json_data(metric,value)\nWHERE metric LIKE '%trafo%' and agent_id = $agent_2 \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensor-Readings Walltime (only important sensors)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load-Sensor-Reading: q_mw (walltime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE metric LIKE '%load%' and metric LIKE '%p_mw' AND (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Load-Sensor-Reading: in_service (walltime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN value = 'true' THEN '1'\n          WHEN value = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE metric LIKE '%load%' and metric LIKE '%in_service' AND (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: p_mw_flex (walltime)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE metric LIKE '%sgen%' and metric LIKE '%p_mw_flex' AND (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: scaling (walltime)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE metric LIKE '%sgen%' and metric LIKE '%scaling' AND (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: in_service (walltime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN value = 'true' THEN '1'\n          WHEN value = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE metric LIKE '%load%' and metric LIKE '%in_service' AND (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Line-Sensor-Reading: loading_percent ($walltime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE metric LIKE '%line%' and metric LIKE '%loading_percent' AND (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Trafo-Sensor-Reading: tap_pos (walltime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE metric LIKE '%trafo%' and metric LIKE '%tap_pos' AND (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Trafo-Sensor-Reading: loading_percent (walltime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE metric LIKE '%trafo%' and metric LIKE '%loading_percent' AND (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Switch-Sensor-Reading: closed (walltime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN json_data.value::json->>'value' = 'true' THEN '1'\n          WHEN json_data.value::json->>'value' = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE metric LIKE '%switch%' and (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Bus-Sensor-Reading: vm_pu (walltime)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "rawSql": "SELECT walltime as \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE metric LIKE '%bus%' and metric LIKE '%vm_pu' AND (agent_id = $agent_1 or agent_id = $agent_2)\nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_1_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true
  },
  {
   "title": "$agent_1_name: Bus-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bus-Sensor-Reading: vm_pu ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%bus%' and metric LIKE '%vm_pu' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Bus-Sensor-Reading: va_degree ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%bus%' and metric LIKE '%va_degree' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_1_name: Line-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Line-Sensor-Reading: loading_percent ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%line%' and metric LIKE '%loading_percent' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Line-Sensor-Reading: in_service ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njsonb_data.metric as metric,\nCAST(case when value = 'true' then '1'\nwhen value = 'false' then '0'\n            \n       end as int)\n\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as jsonb_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%line%' and metric LIKE '%in_service' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::jsonb->>'env')::jsonb->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_1_name: Load-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load-Sensor-Reading: p_mw ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' and metric LIKE '%p_mw' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Load-Sensor-Reading: scaling ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' and metric LIKE '%scaling' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Load-Sensor-Reading: q_mvar ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' and metric LIKE '%q_mvar' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Load-Sensor-Reading: in_service ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN value = 'true' THEN '1'\n          WHEN value = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' and metric LIKE '%in_service' AND agent_id = $agent_1 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_1_name: Sgen-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sgen-Sensor-Reading: p_mw ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%p_mw' AND (agent_id = $agent_1)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: p_mw_flex ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%p_mw_flex' AND (agent_id = $agent_1)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: q_mvar ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%q_mvar' AND (agent_id = $agent_1)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: scaling ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%scaling' AND (agent_id = $agent_1)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: in_service ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN value = 'true' THEN '1'\n          WHEN value = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%in_service' AND (agent_id = $agent_1)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_1_name: Trafo-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trafo-Sensor-Reading: tap_pos ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nvalue::int\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%trafo%' and metric LIKE '%tap_pos' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Trafo-Sensor-Reading: loading_percent ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%trafo%' and metric LIKE '%loading_percent' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Trafo-Sensor-Reading: in_service ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN value = 'true' THEN '1'\n          WHEN value = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%trafo%' and metric LIKE '%in_service' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_1_name: Ext-Grid-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ext-Grid-Sensor-Reading: p_mw ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%ext_grid%' and metric LIKE '%p_mw' AND agent_id = $agent_1 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Ext-Grid-Sensor-Reading: q_mvar ($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%ext_grid%' and metric LIKE '%q_mvar' AND agent_id = $agent_1 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_1_name: Switch-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Switch-Sensor-Reading: closed($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN json_data.value::json->>'value' = 'true' THEN '1'\n          WHEN json_data.value::json->>'value' = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%switch%' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_2_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true
  },
  {
   "title": "$agent_2_name: Bus-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bus-Sensor-Reading: vm_pu ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%bus%' and metric LIKE '%vm_pu' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Bus-Sensor-Reading: va_degree ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%bus%' and metric LIKE '%va_degree' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_2_name: Line-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Line-Sensor-Reading: loading_percent ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%line%' and metric LIKE '%loading_percent' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Line-Sensor-Reading: in_service ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN value = 'true' THEN '1'\n          WHEN value = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%line%' and metric LIKE '%in_service' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_2_name: Load-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load-Sensor-Reading: p_mw ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' and metric LIKE '%p_mw' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Load-Sensor-Reading: scaling ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' and metric LIKE '%scaling' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Load-Sensor-Reading: q_mvar ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' and metric LIKE '%q_mvar' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Load-Sensor-Reading: in_service ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN value = 'true' THEN '1'\n          WHEN value = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%load%' and metric LIKE '%in_service' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_2_name: Sgen-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sgen-Sensor-Reading: p_mw_flex ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%p_mw_flex' AND (agent_id = $agent_2)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: p_mw ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%p_mw' AND (agent_id = $agent_2)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: q_mvar ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%q_mvar' AND (agent_id = $agent_2)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: scaling ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%scaling' AND (agent_id = $agent_2)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Sgen-Sensor-Reading: in_service ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN value = 'true' THEN '1'\n          WHEN value = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%sgen%' and metric LIKE '%in_service' AND (agent_id = $agent_2)\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_2_name: Trafo-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Trafo-Sensor-Reading: loading_percent ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%trafo%' and metric LIKE '%loading_percent' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Trafo-Sensor-Reading: tap_pos ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nvalue::float\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%trafo%' and metric LIKE '%tap_pos' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Trafo-Sensor-Reading: in_service ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN value = 'true' THEN '1'\n          WHEN value = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%trafo%' and metric LIKE '%in_service' AND agent_id = $agent_2\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_2_name: Ext-Grid-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ext-Grid-Sensor-Reading: p_mw ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%ext_grid%' and metric LIKE '%p_mw' AND agent_id = $agent_2 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    },
    {
     "title": "Ext-Grid-Sensor-Reading: q_mvar ($agent_2_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(json_data.value::json->>'value' as float)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njson_each(muscle_actions.sensor_readings::json) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%ext_grid%' and metric LIKE '%q_mvar' AND agent_id = $agent_2 \nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  },
  {
   "title": "$agent_2_name: Switch-Sensor-Readings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "collapsed": true,
   "panels": [
    {
     "title": "Switch-Sensor-Reading: closed($agent_1_name)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "targets": [
      {
       "rawSql": "SELECT ('${start_date}'::TIMESTAMP + '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) - '01:00:00'::time \nas \"time\",\njson_data.metric as metric,\nCAST(CASE WHEN json_data.value::json->>'value' = 'true' THEN '1'\n          WHEN json_data.value::json->>'value' = 'false' THEN '0'\n            \n    END AS int)\nFROM muscle_actions LEFT JOIN episodes ON muscle_actions.id = episodes.muscle_action_id,\njsonb_each(muscle_actions.sensor_readings::jsonb) as json_data(metric,value)\nWHERE episodes.episode = $episode and metric LIKE '%switch%' AND agent_id = $agent_1\nAND ('${start_date}'::TIMESTAMP+ '1 second'::INTERVAL*CAST(((simtimes::json->>'env')::json->>'simtime_ticks') AS INTEGER)) BETWEEN '${start_date}' \nAND '${end_date}' \nORDER BY 1,2"
      }
     ]
    }
   ]
  }
 ]
}