# Generated by Django 4.0.1 on 2024-03-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agentsystemmanagement', '0001_initial'),
        ('competitiondefinitionmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('store_trained_defender', models.BooleanField(default=False, verbose_name='Store copy of trained defender')),
                ('store_trained_attacker', models.BooleanField(default=False, verbose_name='Store copy of trained attacker')),
                ('is_public', models.BooleanField(default=False)),
                ('status', models.CharField(default='created', max_length=20)),
                ('aborted_by_user', models.BooleanField(default=False)),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_enqueued', models.DateTimeField(blank=True, default=None, null=True)),
                ('timestamp_started', models.DateTimeField(blank=True, default=None, null=True)),
                ('timestamp_finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('docker_container_id', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('gpu_id', models.IntegerField(blank=True, default=None, null=True)),
                ('attacker', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackers_received', to='agentsystemmanagement.agent')),
                ('competition', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitiondefinitionmanagement.competitionrun')),
                ('defender', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defenders_received', to='agentsystemmanagement.agent')),
            ],
        ),
    ]
