# Generated by Django 4.0.1 on 2024-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('role', models.CharField(choices=[('B', 'Attacker/Defender'), ('A', 'Attacker'), ('D', 'Defender')], default='B', max_length=1)),
                ('is_public', models.BooleanField(default=False)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('init_yml', models.TextField(blank=True, default=None)),
                ('path_brain_is_correct', models.BooleanField(default=False)),
                ('path_muscle_is_correct', models.BooleanField(default=False)),
                ('path_objective_is_correct', models.BooleanField(default=False)),
            ],
        ),
    ]
